### PR TITLE
[CAMERA]: Implement CAMERA_SetSmoothValue.

### PR DESCRIPTION
**Pull request by Michael0933**

### CODE REVIEW

**Comment by Gh0stBlade** [comment]
Thanks for this, could you also please provide a decomp.me scratch to see how closely this matches the original function?

To also note, we're using the 14/07/1999 build with debugging symbols.

**Comment by Michael0933** [comment]
> Thanks for this, could you also please provide a decomp.me scratch to see how closely this matches the original function?
> 
> To also note, we're using the 14/07/1999 build with debugging symbols.

Thank You for your response.

I am new to this project, I want to contribute more and help with the decompilation process.

Could You provide some help (like instructions or doc) on how to use decomp.me?
And also can You tell me the reason why I should note that we use 14/07/1999 build?

**Comment by Gh0stBlade** [comment]
> > Thanks for this, could you also please provide a decomp.me scratch to see how closely this matches the original function?
> > To also note, we're using the 14/07/1999 build with debugging symbols.
> 
> Thank You for your response.
> 
> I am new to this project, I want to contribute more and help with the decompilation process.
> 
> Could You provide some help (like instructions or doc) on how to use decomp.me? And also can You tell me the reason why I should note that we use 14/07/1999 build?

decomp.me is fairly simple. You paste in the original disassembled function, create a context including all data structures used by the code you decompiled. Then once the scratch is created you replace the function with your own decompiled code as follows:

image

It's a 0% match, looks like there's some operations missing so the original code was doing more than what you decompiled from the looks of it.

The 14/07/1999 version is the latest version of the game known to have matching debugging symbols. Sticking to one version just makes life easier and prevents confusion and code collisions which may occur when merging in code from random builds.

Thank you.

**Comment by Gh0stBlade** [comment]
Implemented in https://github.com/Gh0stBlade/KAIN2/commit/479b8136e7827247b9a1f602bfcf582ae2f9c8a2

**Pull request closed without merging**
